In [1]:
import numpy as np

## Data types and attributes

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [6]:
b = np.array([[1,2.3,3.5],
            [4,5,6.7]])
c = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              
              [[1,2,3],
              [4,5,6],
              [7,8,9]]])
b

array([[1. , 2.3, 3.5],
       [4. , 5. , 6.7]])

In [7]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
a.shape


(2, 3)

In [11]:
b.shape

(2, 3)

In [12]:
c.shape

(2, 3, 3)

In [13]:
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [16]:
a.dtype, b.dtype, c.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [20]:
a.size, b.size, c.size #elem in array

(3, 6, 18)

In [33]:
print(b)
a

[[1.  2.3 3.5]
 [4.  5.  6.7]]


array([1, 2, 3])

In [19]:
import pandas as pd
df = pd.DataFrame(b)
df

0    1    2
0  1.0  2.3  3.5
1  4.0  5.0  6.7

In [24]:
df1 = pd.DataFrame(a)
df1

0
0  1
1  2
2  3

## Creating arrays

In [38]:
ones = np.ones((2,3), int)

In [35]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
zeros = np.zeros((2,3), int)

In [40]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
rarray = np.arange(0,10,2)
rarray

array([0, 2, 4, 6, 8])

In [45]:
random_array = np.random.randint(0, 10, (4,5))

In [46]:
random_array

array([[7, 5, 5, 0, 4],
       [9, 7, 0, 0, 3],
       [7, 1, 7, 5, 6],
       [3, 6, 5, 3, 0]])

In [47]:
random_array_rand = np.random.random((2,3))
random_array_rand

array([[0.46542558, 0.66716938, 0.32944374],
       [0.57202259, 0.32173144, 0.66670708]])

In [55]:
random_array_rand1 = np.random.rand(2,3,2)
random_array_rand1

array([[[0.94012989, 0.61943175],
        [0.75131784, 0.13477238],
        [0.20821499, 0.38667657]],

       [[0.50821439, 0.67531887],
        [0.88228979, 0.53260806],
        [0.65900388, 0.28535469]]])

In [62]:
#Pseudo random numbers
np.random.seed(1)

random_array_4 = np.random.randint(0, 10, (2,3))
random_array_4

array([[5, 8, 9],
       [5, 0, 0]])

## Viewing arrays and matrices

In [63]:
np.unique(random_array)

array([0, 1, 3, 4, 5, 6, 7, 9])

In [64]:
a

array([1, 2, 3])

In [65]:
b

array([[1. , 2.3, 3.5],
       [4. , 5. , 6.7]])

In [66]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [67]:
a[1]

2

In [68]:
b[1]

array([4. , 5. , 6.7])

In [75]:
c[:2,:2,:2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [78]:
four_d = np.random.randint(10, size=(2,3,4,5))
four_d

array([[[[2, 7, 7, 0, 6],
         [5, 1, 4, 6, 0],
         [6, 5, 1, 2, 1],
         [5, 4, 0, 7, 8]],

        [[9, 5, 7, 0, 9],
         [3, 9, 1, 4, 4],
         [6, 8, 8, 9, 2],
         [7, 5, 5, 4, 5]],

        [[8, 5, 8, 1, 1],
         [8, 7, 0, 3, 4],
         [2, 0, 3, 5, 1],
         [2, 4, 3, 0, 6]]],


       [[[0, 7, 2, 8, 3],
         [0, 8, 4, 2, 9],
         [0, 3, 8, 1, 4],
         [3, 3, 6, 7, 3]],

        [[5, 3, 2, 4, 4],
         [0, 3, 3, 8, 3],
         [5, 6, 7, 5, 1],
         [7, 0, 2, 8, 2]],

        [[1, 4, 0, 4, 1],
         [7, 3, 1, 6, 6],
         [9, 6, 9, 6, 0],
         [0, 2, 9, 6, 0]]]])

In [89]:
four_d[1,:1,:2,:4] # four_d[dimension, upper dimension, Rows(elem), Columns(elem)]

array([[[0, 7, 2, 8],
        [0, 8, 4, 2]]])

## Manipulating and comparing arrays

### Arithmetic 

In [90]:
a

array([1, 2, 3])

In [91]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [92]:
a + ones

array([[2, 3, 4],
       [2, 3, 4]])

In [93]:
a - ones

array([[0, 1, 2],
       [0, 1, 2]])

In [94]:
a * ones

array([[1, 2, 3],
       [1, 2, 3]])

In [124]:
b.shape

(2, 3)

In [97]:
a

array([1, 2, 3])

In [96]:
a * b

array([[ 1. ,  4.6, 10.5],
       [ 4. , 10. , 20.1]])

In [107]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [123]:
c.shape

(2, 3, 3)

In [129]:
c = b.reshape(2,3,1) * c

In [130]:
c

array([[[  2.  ,   3.  ,   4.  ],
        [ 14.49,  16.79,  19.09],
        [ 36.75,  40.25,  43.75]],

       [[ 20.  ,  24.  ,  28.  ],
        [ 45.  ,  50.  ,  55.  ],
        [ 91.79,  98.49, 105.19]]])

## Aggregation

In [114]:
a

array([1, 2, 3])

In [119]:
massive_array = np.random.random(10000)
massive_array.size

10000

In [120]:
%timeit sum(massive_array) # python sum
%timeit np.sum(massive_array) #Numpy sum

5.81 ms ± 616 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
40.2 µs ± 5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Numpy in action

In [132]:
from matplotlib.image import imread

<img src="numpy-panda.png" width = "400px" height = "400px"></img>

In [ ]:
panda = imread("numpy-panda.png")

In [134]:
type(panda)

numpy.ndarray

In [136]:
panda.shape, panda.size, panda.ndim

((2330, 3500, 3), 24465000, 3)

In [137]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.